apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dep
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: psni-api-dep
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
