apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dep
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: psni-api-dep
  minReplicas: 3
  maxReplicas: 15
  targetCPUUtilizationPercentage: 60

## https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
