apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep
  labels:
    apptype: psniapp
spec:
  selector:
    matchLabels:
      apptype: psniapp
  template:
    metadata:
      labels:
        apptype: psniapp
    spec:
      containers:
      - name: psni-app
        image: app-image
        ports:
          - containerPort: 8080
            name: web
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "4Gi"
            cpu: "1500m"
        envFrom:
          - secretRef:
              name: envsecrets
        env:
        - name: PORT
          value: '8080'
        - name: LOG_DIR
          value: './logs'
        - name: LOG_FORMAT
          value: combined
        - name: CREDENTIALS
          value: 'true'
        - name: REDIS_PORT
          value: '6379'
        - name: REDIS_HOST
          value: 'redis-master'
        - name: REDIS_DB
          value: '0'
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: redis-password
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP


